const input = require('fs').readFileSync('./arquivo.txt','utf-8')
let dados = input.split(' ')
let a = parseInt(dados[0])
let b = parseInt(dados[1])
let c = parseInt(dados[2])
let vetor = [a, b, c]
vetor.sort((a,b) => a - b)
console.log(vetor[0])
console.log(vetor[1])
console.log(vetor[2])
console.log(' ')
console.log(a)
console.log(b)
console.log(c)
