var input = require('fs').readFileSync('./arquivo.txt','utf-8')
var entrada = input.split('\n')
var idade_dias = parseInt(entrada)
var ano = parseInt(idade_dias / 365)
var resto_mes = idade_dias - (ano * 365)
var mes = parseInt(resto_mes / 30)
var dias = idade_dias - (ano * 365 + mes * 30)
console.log(ano+' anos(s)')
console.log(mes+' mes(es)')
console.log(dias+' dia(s)')